---

image: archlinux

packages:
  - hugo
  - hut

oauth: pages.sr.ht/PAGES:RW

secrets:
  - 5047e926-af42-4c35-aa72-f2cada28b3e7

environment:
  site: blog.karolak.fr

tasks:
  - build: >
      set +x ;
      . ~/.secrets ;
      set -x ;
      cd blog/ ;
      hugo --gc --minify ;
  - publish: >
      tar -C blog/public/ -cvz . > site.tar.gz ;
      hut pages publish -d $site site.tar.gz ;
