image: alpine/latest
packages:
  - make
  - npm
  - py3-pip
sources:
  - https://git.sr.ht/~nka/blog
secrets:
  - 94576db4-37bb-4523-b5c4-033951deacfa
  - dc86411a-dbc5-4742-9af3-132e52133168
environment:
  NETLIFY_AUTH_TOKEN:
tasks:
  - setup: |
      cd blog
      npm install -g netlify-cli
      pip install -r requirements.txt
  - build: |
      cd blog
      make publish
  - deploy: |
      cd blog
      netlify deploy \
        --auth=$(cat ~/.netlify-access-token) \
        --dir=output \
        --prod \
        --site=$(cat ~/.netlify-blog-id) \
        --build
