---

image: alpine/edge
packages:
  - go
  - hugo
  - make
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~sircmpwn/openring
triggers:
  - action: email
    condition: always
    to: Nicolas Karolak <nicolas@karolak.fr>
environment:
  site: blog.karolak.fr
tasks:
  - openring: |
      cd openring
      go build -o openring
      sudo cp openring /usr/bin/
  - build: |
      cd blog
      make build
  - upload: |
      cd blog
      acurl -f https://pages.sr.ht/publish/$site -F content=@site.tar.gz
