image: alpine/latest
secrets:
  - 8a197a79-b688-47cf-8f5c-2ffe1bc2495e
tasks:
  - mirror: |
      cd blog
      #cp -f ~/.ssh/{8a197a79-b688-47cf-8f5c-2ffe1bc2495e,id_rsa}
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git remote add github git@github.com:nikaro/blog.git
      git push github master
