image: alpine/latest
packages:
  - make
  - npm
  - py3-pip
sources:
  - https://git.sr.ht/~nka/blog
secrets:
  - 2c93dcdd-ab19-4fe7-86af-a48cfa32cf07
  - 0ce59312-01e6-4394-9296-e6b9751c5378
tasks:
  - setup: |
      cd blog
      sudo npm install --global netlify-cli
      sudo pip install --requirement requirements.txt
      cat ~/.netlify-auth-token >> ~/.buildenv
      cat ~/.netlify-site-id >> ~/.buildenv
  - build: |
      cd blog
      make publish
  - deploy: |
      cd blog
      netlify deploy \
        --dir=output \
        --prod \
        --build
