content:
  - name: posts
    label: Posts
    type: collection
    path: content/blog
    filename: '{primary}.md'
    fields:
      - name: title
        label: Title
        required: true
        type: text
      - name: date
        label: Date
        required: true
        type: date
      - name: draft
        label: Draft
        type: boolean
    view:
      fields: [ title, date, draft ]
      sort: [ draft, date, title ]
  - name: pages
    label: Pages
    type: collection
    path: content/pages
    filename: '{fields.slug}.md'
    fields:
      - name: title
        label: Title
        required: true
        type: text
      - name: slug
        label: Slug
        required: true
        type: text

media:
  input: static
  output: static
  path: static