---

baseURL: "https://blog.karolak.fr/"
defaultContentLanguage: "fr"
languageCode: "fr-fr"
title: "Blog de Nicolas Karolak"
rssLimit: 10
enableRobotsTXT: true

params:
  email: "blog@karolak.fr"
  liberapay: "https://liberapay.com/nka/"
  cloudflareAnalyticsToken: "d0d27b129da14bc597c9b2b56a081525"

permalinks:
  blog: "/:year/:month/:day/:filename/"
  pages: "/:filename/"

disableKinds: ["taxonomy", "taxonomyTerm", "section"]
