---

baseURL: "https://blog.karolak.fr/"
defaultContentLanguage: "fr"
languageCode: "fr-fr"
title: "Blog de Nicolas Karolak"
rssLimit: 10
enableRobotsTXT: true

params:
  email: "blog@karolak.fr"
  liberapay: "https://liberapay.com/nka/"
  webring:
    - https://www.bortzmeyer.org/feed.atom
    - https://ploum.net/atom.xml
    - https://nourrituresterrestres.substack.com/feed
    - https://n.survol.fr/feed

permalinks:
  blog: "/:year/:month/:day/:filename/"
  pages: "/:filename/"

disableKinds: ["taxonomy", "taxonomyTerm", "section"]
