---

baseURL: "/"
defaultContentLanguage: "fr"
disableKinds: ["taxonomy", "taxonomyTerm", "section"]
enableRobotsTXT: true
languageCode: "fr-fr"
params:
  email: "blog@karolak.fr"
  liberapay: "https://liberapay.com/nka/"
  mastodon: https://piaille.fr/@orak7e
  webring:
    - https://www.bortzmeyer.org/feed.atom
    - https://ploum.net/atom.xml
    - https://www.nourrituresterrestres.fr/feed
    - https://n.survol.fr/feed
permalinks:
  blog: "/:year/:month/:day/:filename/"
  pages: "/:filename/"
rssLimit: 10
title: "Blog de Nicolas Karolak"
