---

baseURL: "https://blog.karolak.fr/"
defaultContentLanguage: "fr"
languageCode: "fr-fr"
title: "Blog de Nicolas Karolak"
rssLimit: 10
enableRobotsTXT: true

params:
  email: "blog@karolak.fr"
  liberapay: "https://liberapay.com/nka/"
  #cloudflareAnalyticsToken: "fa938289bc094ed4a9492db665c3549d"

permalinks:
  blog: "/:year/:month/:day/:filename/"
  pages: "/:filename/"

disableKinds: ["taxonomy", "taxonomyTerm", "section"]
