[build]
publish = "output/"
command = "make publish"

[[redirects]]
from = "/blog"
to = "/"

[[redirects]]
from = "/feed"
to = "/feeds/all.atom.xml"

[[redirects]]
from = "/index.xml"
to = "/feeds/all.atom.xml"

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'none'; style-src 'self'; img-src 'self'; frame-ancestors 'none'"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
