name = "blog-karolak-fr"

[env.production.vars]
GO_VERSION = "1.20.1"
HUGO_VERSION = "0.111.2"
HUGO_baseUrl = "/"

[env.preview.vars]
GO_VERSION = "1.20.1"
HUGO_VERSION = "0.111.2"
HUGO_baseUrl = "/"
HUGO_buildDrafts = true
HUGO_buildFuture = true
