name: CI

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  TASK_X_REMOTE_TASKFILES: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: ghcr.io/nikaro/gha:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: task lint --yes

  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/nikaro/gha:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install tools
        run: brew install hugo

      - name: Build with Hugo
        run: task build --yes

  check:
    name: Check
    permissions: {}
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: always()
    steps:
      - name: Ensure no jobs failed
        run: |-
          [ "${{ !contains(needs.*.result, 'failure') }}" = "true" ] || exit 1
