---
name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@main

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Go
        uses: actions/setup-go@main

      - name: Install Hugo
        run: go install github.com/gohugoio/hugo@latest

      - name: Build with Hugo
        run: make build
