name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  # renovate: datasource=golang-version depName=golang
  GO_VERSION: 1.21.0
  # renovate: datasource=github-releases depName=gohugoio/hugo
  HUGO_VERSION: v0.118.2
  # renovate: datasource=npm depName=netlify-cli
  NETLIFY_VERSION: 16.3.3
  # renovate: datasource=git-tags depName=openring packageName=https://git.sr.ht/~sircmpwn/openring
  OPENRING_VERSION: 1.0.1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ env.GO_VERSION}}

      - name: Install Hugo
        run: go install github.com/gohugoio/hugo@${{ env.HUGO_VERSION }}

      - name: Install Openring
        run: go install git.sr.ht/~sircmpwn/openring@${{ env.OPENRING_VERSION }}

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382 # v3.0.6

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: make build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2.0.0
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@9dbe3824824f8a1377b8e298bafde1a50ede43e5 # v2.0.4
