name: Deploy Hugo site to Netlify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "netlify"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  # renovate: datasource=github-releases depName=gohugoio/hugo
  HUGO_VERSION: v0.118.2
  # renovate: datasource=npm depName=netlify-cli
  NETLIFY_VERSION: 16.3.3
  # renovate: datasource=git-tags depName=openring packageName=https://git.sr.ht/~sircmpwn/openring
  OPENRING_VERSION: 1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    environment:
      name: netlify
      url: https://blog.nikaro.net
    steps:
      - name: Install Hugo
        run: go install github.com/gohugoio/hugo@${{ env.HUGO_VERSION }}

      - name: Install Openring
        run: go install git.sr.ht/~sircmpwn/openring@${{ env.OPENRING_VERSION }}

      - name: Install Netlify CLI
        run: npm install -g netlify-cli@${{ env.NETLIFY_VERSION }}

      - name: Checkout
        run: git clone --depth 1 --branch ${{ github.ref_name }} ${{ github.repositoryUrl }} ${{ github.workspace }}

      - name: Build with Hugo
        run: make build

      - name: Deploy to Netlify
        run: netlify deploy --dir ./public --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
